# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

api_key = app_store_connect_api_key(
  key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
  issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
  key_content: ENV["APP_STORE_CONNECT_KEY_CONTENT"],
  in_house: false # 기업 계정이라면 true
)

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "Tikkeul.xcodeproj")
    build_app(scheme: "Tikkeul")
    upload_to_testflight(
       api_key: api_key
      )
    )
 end
  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number(xcodeproj: "Tikkeul.xcodeproj")
    build_app(scheme: "Tikkeul")
    # - skip_screenshots, skip_metadata: 스크린샷/메타데이터 업로드를 건너뜀
    # - submit_for_review: true면 자동으로 심사 제출
    # - automatic_release: true면 심사 승인 후 자동 출시
    upload_to_app_store(
      api_key: api_key,
      skip_screenshots: true,
      skip_metadata: true,
      submit_for_review: false,  # 필요에 따라 true로 변경
      automatic_release: false   # 필요에 따라 true로 변경
    )
  end

  # 테스트
  lane :test do
   scan(
     scheme: "Tikkeul",
     device: "iPhone 14" 
   )
  end
end
