# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: iOS CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
      - main

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.0'

      - name: Install Dependencies
        run: bundle install

      - name: Install fastlane
        run: brew install fastlane

      - name: Fastlane Test
        env: 
          FASTLANE_SKIP_UPDATE_CHECK: true
        run: bundle exec fastlane test
